language: node_js
sudo: false
node_js: stable
cache:
  directories:
    - bower_components
before_script:
  - npm install -g firebase-tools
  - npm install -g polymer-cli
  - npm install -g bower
script:
  - bower install
  - polymer build
after_success:
  - firebase deploy --token 1/uFN2lGrcDLyZO8qLqUYdcGxAxQYyGVfI_my6eLWrRk_rn8Gz20QUkotIbfXCCda2 --non-interacitve
notifications:
  email:
    on_failure: change
    on_success: change