language: node_js
sudo: false
node_js: stable
cache:
  directories:
    - bower_components
before_script:
  - npm install -g polymer-cli
  - npm install -g bower
  - bower install
  - polymer build
deploy:
  provider: firebase
  token:
    secure: "1/uFN2lGrcDLyZO8qLqUYdcGxAxQYyGVfI_my6eLWrRk_rn8Gz20QUkotIbfXCCda2"